import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";
import { poseidonContract } from "circomlibjs";
import { polkadotHubTestnet } from "../hardhat.config";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

type Deployments = {
	evm: string | null;
	pvm: string | null;
	stealthPayEvm: string | null;
	stealthPayPvm: string | null;
	stealthPayPoolEvm: string | null;
	stealthPayPoolPvm: string | null;
	withdrawVerifierEvm: string | null;
	withdrawVerifierPvm: string | null;
};

function getDefaultDeployments(): Deployments {
	return {
		evm: null,
		pvm: null,
		stealthPayEvm: null,
		stealthPayPvm: null,
		stealthPayPoolEvm: null,
		stealthPayPoolPvm: null,
		withdrawVerifierEvm: null,
		withdrawVerifierPvm: null,
	};
}

function updateDeployments(patch: Partial<Deployments>) {
	let data = getDefaultDeployments();
	try {
		data = { ...data, ...JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8")) };
	} catch {
		// File doesn't exist yet
	}

	data = { ...data, ...patch };
	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: {
\tevm: string | null;
\tpvm: string | null;
\tstealthPayEvm: string | null;
\tstealthPayPvm: string | null;
\tstealthPayPoolEvm: string | null;
\tstealthPayPoolPvm: string | null;
\twithdrawVerifierEvm: string | null;
\twithdrawVerifierPvm: string | null;
} = {
\tevm: ${fmt(data.evm)},
\tpvm: ${fmt(data.pvm)},
\tstealthPayEvm: ${fmt(data.stealthPayEvm)},
\tstealthPayPvm: ${fmt(data.stealthPayPvm)},
\tstealthPayPoolEvm: ${fmt(data.stealthPayPoolEvm)},
\tstealthPayPoolPvm: ${fmt(data.stealthPayPoolPvm)},
\twithdrawVerifierEvm: ${fmt(data.withdrawVerifierEvm)},
\twithdrawVerifierPvm: ${fmt(data.withdrawVerifierPvm)},
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function main() {
	console.log("Deploying StealthPay private pool stack (EVM/solc)...");

	const isTestnet = hre.network.name === "polkadotTestnet";
	const chainOption = isTestnet ? { chain: polkadotHubTestnet } : {};
	const [walletClient] = await hre.viem.getWalletClients(chainOption);
	const publicClient = await hre.viem.getPublicClient(chainOption);

	console.log("Deploying Poseidon hasher...");
	const poseidonHash = await walletClient.deployContract({
		abi: poseidonContract.generateABI(2) as unknown[],
		bytecode: poseidonContract.createCode(2) as `0x${string}`,
	});
	const poseidonReceipt = await publicClient.waitForTransactionReceipt({
		hash: poseidonHash,
		timeout: 120_000,
	});
	if (!poseidonReceipt.contractAddress) {
		throw new Error(`Poseidon deploy tx ${poseidonHash} did not create a contract`);
	}

	console.log("Deploying WithdrawVerifier...");
	const verifierArtifact = await hre.artifacts.readArtifact("WithdrawVerifier");
	const verifierHash = await walletClient.deployContract({
		abi: verifierArtifact.abi,
		bytecode: verifierArtifact.bytecode as `0x${string}`,
	});
	const verifierReceipt = await publicClient.waitForTransactionReceipt({
		hash: verifierHash,
		timeout: 120_000,
	});
	if (!verifierReceipt.contractAddress) {
		throw new Error(`WithdrawVerifier deploy tx ${verifierHash} did not create a contract`);
	}

	console.log("Deploying StealthPayPoolV1...");
	const poolArtifact = await hre.artifacts.readArtifact("StealthPayPoolV1");
	const poolHash = await walletClient.deployContract({
		abi: poolArtifact.abi,
		args: [poseidonReceipt.contractAddress, verifierReceipt.contractAddress],
		bytecode: poolArtifact.bytecode as `0x${string}`,
	});
	const poolReceipt = await publicClient.waitForTransactionReceipt({
		hash: poolHash,
		timeout: 120_000,
	});
	if (!poolReceipt.contractAddress) {
		throw new Error(`StealthPayPoolV1 deploy tx ${poolHash} did not create a contract`);
	}

	console.log(`WithdrawVerifier deployed to: ${verifierReceipt.contractAddress}`);
	console.log(`StealthPayPoolV1 deployed to: ${poolReceipt.contractAddress}`);

	updateDeployments({
		stealthPayPoolEvm: poolReceipt.contractAddress,
		withdrawVerifierEvm: verifierReceipt.contractAddress,
	});
	console.log("Updated deployments.json");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
