import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";
import { polkadotHubTestnet } from "../hardhat.config";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

type Deployments = {
	evm: string | null;
	pvm: string | null;
	stealthPayEvm: string | null;
	stealthPayPvm: string | null;
	stealthPayPoolEvm: string | null;
	stealthPayPoolPvm: string | null;
	withdrawVerifierEvm: string | null;
	withdrawVerifierPvm: string | null;
};

function getDefaultDeployments(): Deployments {
	return {
		evm: null,
		pvm: null,
		stealthPayEvm: null,
		stealthPayPvm: null,
		stealthPayPoolEvm: null,
		stealthPayPoolPvm: null,
		withdrawVerifierEvm: null,
		withdrawVerifierPvm: null,
	};
}

function updateDeployments(key: keyof Deployments, address: string) {
	let data = getDefaultDeployments();
	try {
		data = { ...data, ...JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8")) };
	} catch {
		// File doesn't exist yet
	}
	data[key] = address;

	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: {
\tevm: string | null;
\tpvm: string | null;
\tstealthPayEvm: string | null;
\tstealthPayPvm: string | null;
\tstealthPayPoolEvm: string | null;
\tstealthPayPoolPvm: string | null;
\twithdrawVerifierEvm: string | null;
\twithdrawVerifierPvm: string | null;
} = {
\tevm: ${fmt(data.evm)},
\tpvm: ${fmt(data.pvm)},
\tstealthPayEvm: ${fmt(data.stealthPayEvm)},
\tstealthPayPvm: ${fmt(data.stealthPayPvm)},
\tstealthPayPoolEvm: ${fmt(data.stealthPayPoolEvm)},
\tstealthPayPoolPvm: ${fmt(data.stealthPayPoolPvm)},
\twithdrawVerifierEvm: ${fmt(data.withdrawVerifierEvm)},
\twithdrawVerifierPvm: ${fmt(data.withdrawVerifierPvm)},
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function main() {
	console.log("Deploying ProofOfExistence (EVM/solc)...");

	const isTestnet = hre.network.name === "polkadotTestnet";
	const chainOption = isTestnet ? { chain: polkadotHubTestnet } : {};

	const [walletClient] = await hre.viem.getWalletClients(chainOption);
	const publicClient = await hre.viem.getPublicClient(chainOption);
	const artifact = await hre.artifacts.readArtifact("ProofOfExistence");

	const hash = await walletClient.deployContract({
		abi: artifact.abi,
		bytecode: artifact.bytecode as `0x${string}`,
	});

	const receipt = await publicClient.waitForTransactionReceipt({
		hash,
		timeout: 120_000,
	});

	if (!receipt.contractAddress) {
		throw new Error(`Deploy tx ${hash} did not create a contract`);
	}

	console.log(`EVM ProofOfExistence deployed to: ${receipt.contractAddress}`);
	updateDeployments("evm", receipt.contractAddress);
	console.log("Updated deployments.json");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
