export const privatePoolAbi = [
	{
		type: "function",
		name: "DENOMINATION",
		inputs: [],
		outputs: [{ name: "", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "MAX_RELAYER_FEE",
		inputs: [],
		outputs: [{ name: "", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "TREE_DEPTH",
		inputs: [],
		outputs: [{ name: "", type: "uint8" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "scope",
		inputs: [],
		outputs: [{ name: "", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "latestRoot",
		inputs: [],
		outputs: [{ name: "", type: "bytes32" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "nextIndex",
		inputs: [],
		outputs: [{ name: "", type: "uint32" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "filledSubtrees",
		inputs: [{ name: "", type: "uint256" }],
		outputs: [{ name: "", type: "bytes32" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "deposit",
		inputs: [{ name: "commitment", type: "bytes32" }],
		outputs: [
			{ name: "leafIndex", type: "uint32" },
			{ name: "root", type: "bytes32" },
		],
		stateMutability: "payable",
	},
	{
		type: "function",
		name: "withdraw",
		inputs: [
			{ name: "pA", type: "uint256[2]" },
			{ name: "pB", type: "uint256[2][2]" },
			{ name: "pC", type: "uint256[2]" },
			{ name: "root", type: "bytes32" },
			{ name: "nullifierHash", type: "bytes32" },
			{ name: "recipient", type: "address" },
			{ name: "relayer", type: "address" },
			{ name: "fee", type: "uint256" },
			{ name: "expiry", type: "uint256" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "computeContext",
		inputs: [
			{ name: "recipient", type: "address" },
			{ name: "relayer", type: "address" },
			{ name: "fee", type: "uint256" },
			{ name: "expiry", type: "uint256" },
		],
		outputs: [{ name: "", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "isKnownRoot",
		inputs: [{ name: "root", type: "bytes32" }],
		outputs: [{ name: "", type: "bool" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "nullifierHashes",
		inputs: [{ name: "", type: "bytes32" }],
		outputs: [{ name: "", type: "bool" }],
		stateMutability: "view",
	},
	{ type: "error", name: "FeeTooHigh", inputs: [] },
	{ type: "error", name: "InvalidDenomination", inputs: [] },
	{ type: "error", name: "InvalidFieldElement", inputs: [] },
	{ type: "error", name: "InvalidProof", inputs: [] },
	{ type: "error", name: "NullifierAlreadyUsed", inputs: [] },
	{ type: "error", name: "QuoteExpired", inputs: [] },
	{ type: "error", name: "TransferFailed", inputs: [] },
	{ type: "error", name: "TreeFull", inputs: [] },
	{ type: "error", name: "UnknownRoot", inputs: [] },
	{
		type: "event",
		name: "Deposit",
		inputs: [
			{ indexed: true, name: "commitment", type: "bytes32" },
			{ indexed: false, name: "leafIndex", type: "uint32" },
			{ indexed: false, name: "root", type: "bytes32" },
		],
	},
	{
		type: "event",
		name: "Withdrawal",
		inputs: [
			{ indexed: true, name: "recipient", type: "address" },
			{ indexed: true, name: "relayer", type: "address" },
			{ indexed: false, name: "nullifierHash", type: "bytes32" },
			{ indexed: false, name: "fee", type: "uint256" },
		],
	},
] as const;
