import { useMemo, useState } from "react";
import { useLocation } from "react-router-dom";

import { buildClaimRouteLinkFromSearch, parseClaimLinkSearch } from "../utils/claimLinks";
import { listBrowserExtensions } from "../wallet/stealthRegister";

function maskAddress(value: string | null) {
	if (!value) {
		return "Unknown recipient";
	}
	return `${value.slice(0, 8)}...${value.slice(-6)}`;
}

export default function GiftLinkPage() {
	const location = useLocation();
	const hint = useMemo(() => parseClaimLinkSearch(location.search), [location.search]);
	const isBearerGift = hint.mode === "bearer";
	const hasAnyGiftParam = useMemo(() => {
		const params = new URLSearchParams(location.search);
		return ["mode", "pool", "registry", "recipient", "memo", "key", "tx"].some((key) =>
			params.has(key),
		);
	}, [location.search]);
	const hasGiftContext =
		Boolean(hint.poolAddress) &&
		Boolean(hint.registryAddress) &&
		(isBearerGift
			? Boolean(hint.memoHash) && Boolean(hint.giftKey)
			: Boolean(hint.recipientOwner));
	const hasInvalidGiftContext = hasAnyGiftParam && !hasGiftContext;
	const claimHref = hasGiftContext ? buildClaimRouteLinkFromSearch(location.search) : "#/claim";
	const advancedClaimHref = hasGiftContext ? `#/withdraw${location.search}` : "#/withdraw";
	const [linkCopied, setLinkCopied] = useState(false);
	const canNativeShare =
		typeof navigator !== "undefined" && typeof navigator.share === "function";
	const hasExtensionWallets = listBrowserExtensions().length > 0;
	const shouldReopenInWalletBrowser = hasGiftContext && !isBearerGift && !hasExtensionWallets;
	const isCompactDevice =
		typeof window !== "undefined" && window.matchMedia("(max-width: 768px)").matches;

	const environmentNote = !shouldReopenInWalletBrowser
		? null
		: isCompactDevice
			? "This browser does not expose a wallet extension right now. Copy this gift link and reopen it in a desktop browser or wallet-enabled browser to claim."
			: "No browser extension wallet was detected here. Copy this gift link and reopen it in a browser with your recipient wallet extension installed.";

	async function copyGiftLink() {
		await navigator.clipboard.writeText(window.location.href);
		setLinkCopied(true);
	}

	async function shareGiftLink() {
		if (!canNativeShare) {
			return;
		}
		await navigator.share({
			title: "Private gift",
			text: "Open this private gift in StealthPay.",
			url: window.location.href,
		});
	}

	return (
		<div className="space-y-6 animate-fade-in">
			<div className="gift-panel space-y-5">
				<div className="flex flex-wrap items-start justify-between gap-4">
					<div className="space-y-3 max-w-3xl">
						<span className="gift-chip">
							{hasGiftContext
								? "Private gift received"
								: hasInvalidGiftContext
									? "Gift link incomplete"
									: "Gift link needed"}
						</span>
						<h1 className="page-title">
							{hasGiftContext
								? "Someone sent you a private gift"
								: hasInvalidGiftContext
									? "This gift link is incomplete"
									: "Open a private gift link"}
						</h1>
						<p className="text-sm text-text-secondary">
							{!hasGiftContext
								? hasInvalidGiftContext
									? "The QR or link opened StealthPay, but it is missing required claim data. Ask the sender for the full private gift link or QR."
									: "Scan a StealthPay QR or open the private gift link you received. The link preloads the encrypted gift context so the app can guide the claim."
								: isBearerGift
									? "This walletless gift link or QR opens a private claim flow. Keep it private until you claim."
									: "This gift link or QR opens a private claim flow powered by StealthPay. Your gift is claimed through the privacy pool and relayer rather than appearing as a direct public payment to your wallet."}
						</p>
					</div>
					<div className="paper-surface min-w-[220px] px-4 py-4">
						<div className="text-xs uppercase tracking-[0.18em] text-text-muted">
							{hasGiftContext
								? "Gift size"
								: hasInvalidGiftContext
									? "Invalid link"
									: "Waiting for link"}
						</div>
						<div className="mt-2 text-lg font-semibold text-text-primary">
							{hasGiftContext
								? "1 UNIT"
								: hasInvalidGiftContext
									? "Cannot open gift"
									: "No gift loaded"}
						</div>
						<p className="mt-2 text-sm text-text-secondary">
							{!hasGiftContext
								? hasInvalidGiftContext
									? "A valid gift needs pool, registry, and either recipient details or bearer key data."
									: "Use the exact private gift link or QR generated by the sender."
								: isBearerGift
									? "Open the gift to continue with email or passkey and claim privately."
									: "Open the gift to connect the recipient wallet and continue privately."}
						</p>
					</div>
				</div>

				{hasGiftContext ? (
					<div className="grid gap-3 md:grid-cols-3">
						<div className="gift-step">
							<div className="text-xs uppercase tracking-[0.18em] text-text-muted">
								Recipient hint
							</div>
							<div className="mt-2 text-sm font-medium text-text-primary">
								{isBearerGift
									? "No wallet needed yet"
									: maskAddress(hint.recipientOwner)}
							</div>
							<p className="mt-2 text-sm text-text-secondary">
								{isBearerGift
									? "Sign in to StealthPay when a social wallet provider is configured."
									: "This link is intended for the wallet that matches the hidden private claim."}
							</p>
						</div>
						<div className="gift-step">
							<div className="text-xs uppercase tracking-[0.18em] text-text-muted">
								Private claim
							</div>
							<div className="mt-2 text-sm font-medium text-text-primary">
								{isBearerGift ? "Continue and claim" : "Claim through the relayer"}
							</div>
							<p className="mt-2 text-sm text-text-secondary">
								{isBearerGift
									? "StealthPay claims to a recoverable wallet when available."
									: "The app will guide the recipient wallet directly into the private claim flow."}
							</p>
						</div>
						<div className="gift-step">
							<div className="text-xs uppercase tracking-[0.18em] text-text-muted">
								Privacy
							</div>
							<div className="mt-2 text-sm font-medium text-text-primary">
								No direct sender-to-wallet transfer
							</div>
							<p className="mt-2 text-sm text-text-secondary">
								The public chain sees pool interactions instead of a simple public
								payment trail.
							</p>
						</div>
					</div>
				) : (
					<div className="paper-surface px-4 py-4 text-sm text-text-secondary">
						{hasInvalidGiftContext
							? "This QR or link is missing required claim data, so StealthPay cannot safely start the claim flow. Ask the sender to resend the private gift QR or link from the gift success screen."
							: "This page does not have a gift attached yet. If you scanned a QR and landed here, ask the sender for the full StealthPay private gift QR or link. You can still open the claim flow directly or use advanced claim tools if needed."}
					</div>
				)}

				{environmentNote ? (
					<div className="soft-warning">
						<div className="font-semibold">Wallet browser needed</div>
						<p className="mt-1 text-text-secondary">{environmentNote}</p>
					</div>
				) : null}

				<div className="flex flex-wrap gap-3">
					{shouldReopenInWalletBrowser ? (
						<button type="button" className="btn-primary" onClick={copyGiftLink}>
							{linkCopied ? "Gift Link Copied" : "Copy and Reopen"}
						</button>
					) : (
						<a href={claimHref} className="btn-primary">
							{hasGiftContext
								? isBearerGift
									? "Sign in and open gift"
									: "Open Gift"
								: hasInvalidGiftContext
									? "Open Claim Tools"
									: "Open Claim Tools"}
						</a>
					)}
					{hasGiftContext && canNativeShare ? (
						<button type="button" className="btn-secondary" onClick={shareGiftLink}>
							Share Gift Link
						</button>
					) : null}
					{shouldReopenInWalletBrowser ? (
						<a href={claimHref} className="btn-secondary">
							Continue Here Anyway
						</a>
					) : (
						hasGiftContext ? (
							<button type="button" className="btn-secondary" onClick={copyGiftLink}>
								{linkCopied ? "Gift Link Copied" : "Copy Gift Link"}
							</button>
						) : null
					)}
					<a href={advancedClaimHref} className="btn-secondary">
						Recovery Tools
					</a>
				</div>
			</div>
		</div>
	);
}
